[package]
name = "basebuilder"
version = "0.1.0"
authors = ["Simon Voordouw <simonvoordouw@gmail.com>"]
edition = "2021"

[features]
inspector = ["dep:bevy-inspector-egui", "iyes_loopless/bevy-inspector-egui"]

[profile.small-release]
inherits = "release"
lto = "fat"
opt-level = "z"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
iyes_loopless = "0.9.1"
bevy = { version = "0.9", features = ["wayland"] }
bevy-inspector-egui = { version = "0.17.0", optional = true }
ndarray = "0.15.6"
bevy_ecs_tilemap = "0.9.0"
bevy_rapier2d = { version = "0.20.0", features = ["wasm-bindgen"] }